<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__username_show</name>
   <tag></tag>
   <elementGuidId>64defdfb-34f1-4ba6-9e72-093ce4fa971b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#username_show</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='username_show']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#username_show</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>844c144d-8856-484c-875c-56f211b4df66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7733ecc1-5a02-4e51-8636-48823fd9a988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username_show</value>
      <webElementGuid>cb7d9a89-d19c-4455-b6b8-a31a6825f932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>username_show</value>
      <webElementGuid>d88ed478-1cc2-427a-a111-5a5738f90aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_show</value>
      <webElementGuid>bb4db526-a98e-449e-932b-8ca22a9681ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Hello Shanmathi22!</value>
      <webElementGuid>bcb0e376-1315-4394-ae4d-959a1dcc6ef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;username_show&quot;)</value>
      <webElementGuid>67863d13-85e6-461b-b9e5-fdd3a1d9c17f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='username_show']</value>
      <webElementGuid>e5fd0add-f225-49ab-9117-5e6dd8a78c29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>33f5995c-9c79-4fc5-ba52-acb3ec199d32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'username_show' and @id = 'username_show']</value>
      <webElementGuid>1e064873-51a5-4cc5-a783-6fde61272e20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
