<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Invalid Login details or Your Password might have expired</name>
   <tag></tag>
   <elementGuidId>b6968b72-bd30-4a6f-bbd2-0b97d4364ad8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='login_form']/table/tbody/tr[5]/td[2]/div/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Invalid Login details or Your Password might have expired. Click here to reset y&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>4d1d929e-5d1d-4974-b1ff-8781872bbfef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invalid Login details or Your Password might have expired. Click here to reset your password</value>
      <webElementGuid>07e3e2e7-2498-481f-9866-940c6da9cc93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_form&quot;)/table[@class=&quot;login&quot;]/tbody[1]/tr[5]/td[2]/div[@class=&quot;auth_error&quot;]/b[1]</value>
      <webElementGuid>6148fc5e-c9a9-4817-9764-909cd8ee523d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login_form']/table/tbody/tr[5]/td[2]/div/b</value>
      <webElementGuid>430c4bc1-f8af-446b-ad17-87f305999d4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password?'])[1]/following::b[1]</value>
      <webElementGuid>0d360144-c12f-403f-a665-f3486dad3a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New User Register Here'])[1]/preceding::b[1]</value>
      <webElementGuid>b72f2576-420f-4c63-bbc6-a79eb53cc887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Invalid Login details or Your Password might have expired.']/parent::*</value>
      <webElementGuid>2863b89c-7d95-4e75-a9cb-0a712cb931f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b</value>
      <webElementGuid>6e3ba53f-2015-46c0-b45b-c7501f4a610d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'Invalid Login details or Your Password might have expired. Click here to reset your password' or . = 'Invalid Login details or Your Password might have expired. Click here to reset your password')]</value>
      <webElementGuid>4bf09f15-26cf-411f-bef0-54552ad180cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
