<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select Room Type</name>
   <tag></tag>
   <elementGuidId>28ca5ed9-4ad7-4d7d-b292-d4c4e0fe679e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='room_type']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#room_type</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#room_type</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7ba25018-9e4c-4340-ac44-fb19f185d57d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>room_type</value>
      <webElementGuid>9d27a1f7-f9dd-4f86-9985-08c8fb22faf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>room_type</value>
      <webElementGuid>c329a531-2264-492a-a075-7ea35f8c0f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search_combobox</value>
      <webElementGuid>e396625b-c3cd-42da-8388-26675e3612ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            - Select Room Type -
            Standard
            Double
            Deluxe
            Super Deluxe
          </value>
      <webElementGuid>e8ba735d-6a50-4e89-867a-0716b3631792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;room_type&quot;)</value>
      <webElementGuid>577ea833-b783-4ccc-958e-c2d631d9bbf5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='room_type']</value>
      <webElementGuid>457d2c7f-54da-4d67-b795-c151b3668f8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_form']/table/tbody/tr[4]/td[2]/select</value>
      <webElementGuid>fed36684-7bfd-49bb-af5d-6570ace44009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::select[1]</value>
      <webElementGuid>10daa9f2-7513-4d86-a3e7-6bbbffb7eef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/select</value>
      <webElementGuid>4d8ff21c-8c1c-4166-8204-ab4631ba9cac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'room_type' and @id = 'room_type' and (text() = '
            - Select Room Type -
            Standard
            Double
            Deluxe
            Super Deluxe
          ' or . = '
            - Select Room Type -
            Standard
            Double
            Deluxe
            Super Deluxe
          ')]</value>
      <webElementGuid>b50d96df-8988-4a97-b78c-81a2f38af228</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
