<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Please Select Adults per Room</name>
   <tag></tag>
   <elementGuidId>5cb58bb8-1205-4669-bbd0-4ab349f91710</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='adults_room_span']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#adults_room_span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Please Select Adults per Room&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d7ccf3e1-1e66-408a-a3d0-6751f6d25f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>adults_room_span</value>
      <webElementGuid>e5f8ff42-9b06-4711-b734-29099ecdceb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>reg_error</value>
      <webElementGuid>f9f0024b-a174-44f6-8429-ec7dd07d007c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please Select Adults per Room</value>
      <webElementGuid>a406865e-0433-4936-be61-1e2c652d4917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;adults_room_span&quot;)</value>
      <webElementGuid>a43e02f8-f2fa-4d9e-8994-ee0bc90778a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='adults_room_span']</value>
      <webElementGuid>69bf8623-86eb-4e2e-ab51-476204b9edf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_form']/table/tbody/tr[8]/td[2]/span</value>
      <webElementGuid>ff028d9c-1bd3-4122-b658-6d70fe420453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::span[1]</value>
      <webElementGuid>257f6850-7056-4995-ac2b-c88e60986629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please Select Adults per Room']/parent::*</value>
      <webElementGuid>0e09c1d7-3e5d-429f-a8c7-734039fa9e62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[2]/span</value>
      <webElementGuid>563334f0-3caa-4fe7-bb6c-f74ce12432b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'adults_room_span' and (text() = 'Please Select Adults per Room' or . = 'Please Select Adults per Room')]</value>
      <webElementGuid>6c6b81b2-3f43-4be9-800f-66907ffbb14b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
