<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Total Price (excl. GST)_radiobutton_0</name>
   <tag></tag>
   <elementGuidId>650f50cb-9952-4856-a7ed-9cc03c2de3f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radiobutton_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radiobutton_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#radiobutton_0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7869a9d0-3ba1-489b-9457-ebfd5454371a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radiobutton_0</value>
      <webElementGuid>3103c75a-a4d9-40b7-aa24-90f44168efe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radiobutton_0</value>
      <webElementGuid>18a79729-3828-4289-ba8b-dfde7fc00361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>2d484957-da67-487b-8210-a3ebd46cfe16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a24b066a-6786-49d6-b8f6-6f553f5592d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radiobutton_0&quot;)</value>
      <webElementGuid>28328059-85c8-49e2-810a-805ee9da2a18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radiobutton_0']</value>
      <webElementGuid>477bb570-a4fd-44a7-b4ad-5edffafb2e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='select_form']/table/tbody/tr[2]/td/table/tbody/tr[2]/td/input</value>
      <webElementGuid>9f1710a1-e0cf-42bb-b187-65dbf5a9d50e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d7a72cb8-8e17-45b5-ab48-be71d1274a3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'radiobutton_0' and @id = 'radiobutton_0' and @type = 'radio']</value>
      <webElementGuid>180ccdd0-2410-4cac-b005-0d3e27fe984c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
