<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Cancel_OrderIDBTn</name>
   <tag></tag>
   <elementGuidId>34f22ec0-62d5-49f8-83a4-e2266dc4b08b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btn_id_1228335']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_id_1228335</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Cancel 651871K00E&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ebd02f4-f666-491f-b0d3-34141e5a5a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn_id_1228335</value>
      <webElementGuid>fcace236-5eee-4902-ae96-2784dbf4062c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_id_1228335</value>
      <webElementGuid>2553fc1e-6463-4751-9311-a5a1cfe86f1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e62e3dc8-0fd1-4501-8920-3d1c1c1920ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Cancel 651871K00E</value>
      <webElementGuid>0c6f5943-8ca8-47ba-8627-8bb6af556fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>cancel_booking('1228335','651871K00E');</value>
      <webElementGuid>e2f9c9f4-63df-450c-acbb-4b8fce5fb2df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_id_1228335&quot;)</value>
      <webElementGuid>039dbfdf-6656-4e17-a04d-0c77e96ed0cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn_id_1228335']</value>
      <webElementGuid>eaaea13c-909c-442a-ae38-fefb162efa85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='booked_form']/table/tbody/tr[2]/td/table/tbody/tr[2]/td[3]/input</value>
      <webElementGuid>3f7bd9d4-0796-42da-b63e-002726fa6ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/input</value>
      <webElementGuid>a69a46b4-e518-4aaa-929d-4de83ac81a59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'btn_id_1228335' and @id = 'btn_id_1228335' and @type = 'button']</value>
      <webElementGuid>4f831703-40e1-4b3b-95c3-4cfbc9686ab1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
