<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Please Select a Hotel</name>
   <tag></tag>
   <elementGuidId>c5f95a9d-2efd-4b09-97de-da3cb6d44c87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='radiobutton_span']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radiobutton_span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Please Select a Hotel&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>221c78cc-f47a-439c-a5da-c859ab3ecea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radiobutton_span</value>
      <webElementGuid>6f6ee9d0-818d-4edc-b48a-cb24cce30727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>reg_error</value>
      <webElementGuid>fe4de454-634b-46b1-a2ad-ac3673aa12b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please Select a Hotel</value>
      <webElementGuid>d1d274ad-11a2-4ca0-ae8c-82c4dee39fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radiobutton_span&quot;)</value>
      <webElementGuid>bbf4351e-63ff-4bcf-945c-507a7509a6f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='radiobutton_span']</value>
      <webElementGuid>7cf1ef64-92b8-47b6-a8cd-879e99f3b4a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='select_form']/table/tbody/tr[3]/td/label</value>
      <webElementGuid>635fb082-a8b1-4f7a-9c85-95fff625d1b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Price (excl. GST)'])[1]/following::label[1]</value>
      <webElementGuid>cc4c21ea-adac-4583-9db1-8b020307d739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price per Night'])[1]/following::label[1]</value>
      <webElementGuid>af1971ef-144a-4a9b-b217-40267fcd2a85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adactin.com'])[1]/preceding::label[1]</value>
      <webElementGuid>d8a93908-8096-4693-a0c0-d0093d7a9096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please Select a Hotel']/parent::*</value>
      <webElementGuid>ca2e4a42-2e56-4301-87e6-0632fde29541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>1ca18b2f-18fd-42d1-9d24-ab35db5836e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'radiobutton_span' and (text() = 'Please Select a Hotel' or . = 'Please Select a Hotel')]</value>
      <webElementGuid>b51ef484-0439-434b-947b-849c3684e21c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
