<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Register</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>82b9789d-d028-4d3f-87ee-3d93b034e41c</testSuiteGuid>
   <testCaseLink>
      <guid>7cfe646c-f104-4d2a-ace2-6093a38c44b8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdactinHotel/Register/TC_003_NewRegistrationFormPageOpen</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>d1e99c7f-3b92-4a32-991e-f99bb7e4436e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdactinHotel/Register/TC_004_RegisterWithoutMandatoryFields</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4517a5b9-14e1-4c48-8fcf-c6a8919cffa2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c87b0ff6-a1e3-4a0e-8a48-d59b80e9a212</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6b82695-a8bd-4586-9be4-cc01e77076d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25896508-ee2d-4302-bb71-4b1b5c61387b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82f4c291-b46b-4438-a097-c36478599bbe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6c90cea-f23f-44b8-bac5-b62fd3defe92</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6219d7a-0921-4238-96ac-aa3b45090800</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a08cf1fd-8d60-4fdd-8e93-931c8e280ac1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e06427db-012c-433d-ac8f-1730fc1f5d3a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdactinHotel/Register/TC_005_WithoutUserName</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66e246ce-871d-4c37-be73-accae9eacc93</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>542b6152-46f8-49e6-ac67-dc6877f50901</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdactinHotel/Register/TC_006_WithoutPassword</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>419b8469-9a11-4614-bbf2-1b6bf863296f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3305bc09-4fb2-49a3-abdf-73aaa85ab6fe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dd599427-8c9e-4014-ac26-278dfc89fb34</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdactinHotel/Register/TC_007_WithoutConfirmPassword</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b001387-ddb1-46a6-8002-a1398ffbeb6d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb2efc17-2234-4a89-a489-d4013cc125c5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fb4c5893-e53b-4782-a225-ab9d46a80ee3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdactinHotel/Register/TC_008_WithoutFullName</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18601cea-c052-4fce-8097-ef2dca171678</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b75a598-0e84-458f-96bc-19cdb4a35d9c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>56d9b58c-158d-499e-99bf-9e38dc9f521a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdactinHotel/Register/TC_009_WithoutEmail</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5a33a87-ace4-4243-9990-398d1f9a634d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>34feb492-4721-4e66-b0a0-83fbc926b98f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdactinHotel/Register/TC_010_WithoutCaptcha</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94097ad3-35ca-4804-9100-2a8d7ac2759c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f6ba31e7-2976-4241-b6b4-909ebcdeac2b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdactinHotel/Register/TC_011_WithoutTermsAndConditions</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>813e032c-075e-4ff4-8607-2e8ac2f01f92</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>91377adb-0e36-4464-8a74-2ba2aef1154d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdactinHotel/Register/TC_012_LessThan5digtsPassword</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>224fe3e6-576f-4138-9ab3-4bfa55afcbf7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c79cdc7-e78d-4f7b-9caa-f33aa5971da9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5b13054a-f811-4b44-a637-6497fcf0f31d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdactinHotel/Register/TC_013_DifferentPasswords</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d98056a4-31d2-4e1e-bfd1-375fc9f67e03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85f2b588-307a-4dd1-b59d-7485f6551709</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bfdeba5f-93a6-40c7-82b0-1d807b5fb6fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdactinHotel/Register/TC_014_LessThanUsername</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>221500d3-e73e-4076-8d2b-7ad116171a1d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9beb15d4-8788-4043-9391-c7908acb3a2b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdactinHotel/Register/TC_015_InvalidEmail</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad033da5-f578-44f0-b735-61175753ef1e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
