<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SearchHotel</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>e25ab205-b2ab-4855-83fd-f693171ec55c</testSuiteGuid>
   <testCaseLink>
      <guid>ed117e5f-9a90-458b-881d-20f80d3b2fa5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdactinHotel/SearchHotel/TC_001_MandatoryFields</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e8be178-7ac0-4711-afe3-6ae5535b0bb6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90a2f12b-58f9-42d2-b2b1-c9579dc49169</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>edc08aca-f994-4cda-963d-f5264553ac24</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdactinHotel/SearchHotel/TC_002_OptionalFields</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4fb5d0a5-b9f3-4ec1-a262-ec2e68fc8dfb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>daf69ab8-3743-4c83-b7ce-24cf41c1d4f8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdactinHotel/SearchHotel/TC_003_MadatoryFields_ExceptLocation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>62fefe39-6d3b-40e3-a0b6-cde629f3bc7e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdactinHotel/SearchHotel/TC_004_MandatoryFields_ExceptNoOfRooms</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f11f5b4-08b0-419d-acd6-d8bd25bc885d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>daf97cc1-6664-45f0-99b0-bdab46621c86</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>84dcc34e-63bc-48f5-bc1c-c6518c629cc9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdactinHotel/SearchHotel/TC_005_MandatoryFields_ExceptCheckInDate</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb1eccc5-81f2-423d-be45-866aba24dae9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b75a4b9d-8bfa-4617-ae75-f422c7c10554</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7ca64e42-d3cb-4e0f-9fce-86269590bfd4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdactinHotel/SearchHotel/TC_006_MandatoryField_ExceptCheckOutDate</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09620dd9-3c85-4343-8a1d-565a59d49d7b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a075b20-240e-4d38-9dde-c8d3c622d530</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3aaa6dc8-aed4-4475-9f54-49a26e57a5cc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdactinHotel/SearchHotel/TC_007_MandatoryFields_ExceptAdultsPerRoom</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6469b65-55aa-4560-b31b-bd42d5cbe804</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76b66658-599f-4baa-9490-d1f28153e2fc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6e495e64-3558-40e1-8f45-49a6e3828f72</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdactinHotel/SearchHotel/TC_008_Reset</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1ca2d1f-f847-401b-a617-a679f716b66f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f3e8e3b-79a4-42cc-93a0-7095db5b23fd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>174a112e-d60a-4d03-8a78-e0e6ddb5fa47</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdactinHotel/SearchHotel/TC_009_BookItineraryMenu</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>657e2de2-59b4-4669-82f4-fd05fe3af94c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d8b6122-fa6d-480e-86af-c8c5b9de2673</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9818e165-6d8b-4d35-ba4c-cddce12762fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdactinHotel/SearchHotel/TC_010_ChangePasswordMenu</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e21d6da2-721f-4090-a1aa-d35e874e30b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa2fb9b7-e4e5-4a7c-8c53-9fa66945b230</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>90171474-186b-4dcd-9128-50bbaf114159</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdactinHotel/SearchHotel/TC_011_LogoutMenu</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
