<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SelectHotel</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>728cb568-009e-42d7-9889-d2f300ee6b29</testSuiteGuid>
   <testCaseLink>
      <guid>af04cfbf-b439-478a-9025-5192092ecb07</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdactinHotel/Select hotel/TC_001_SelectHotel</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b50a2d34-2f51-4ab1-b913-7449b1324d64</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d784cb3-4e33-493c-99e2-4afbcb440847</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f93a231-8d50-4d0a-9bdc-a3c71f1aa8da</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>169fbe46-f0fa-49d3-8bc6-adce130088d0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdactinHotel/Select hotel/TC_002_ErrorMessageDisplay</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d306f5cc-59bc-45f1-8180-186b21c303a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffee6d78-fed8-4bb9-b18c-cce2749511c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2946f4b-c598-49dd-a16e-80f0e16d15d6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c7b91ce4-3a20-46f5-9583-9119a57b5a79</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdactinHotel/Select hotel/TC_003_SelectHotel_CancelButton</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04ab232a-48b6-430a-9673-c89f405d87e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5544be56-cd0f-42de-88e2-dd6854db4725</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7391e178-d6e8-4498-a12e-214219b005a2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fe7e65c1-6ea6-4d39-a22a-e3f30435faa6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdactinHotel/Select hotel/TC_004_CancelButton</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>671496b4-161a-4999-9c70-c3db9f857482</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30b92c72-60ed-49d2-be4b-98b8427f253d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8fb161e-55ee-49fb-b10e-ee44e64db6a3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>76328ee0-ba8c-4c01-bbbe-f8c61b556426</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdactinHotel/Select hotel/TC_005_BookedItenerary</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e9b8fa1-a9f2-4f19-a613-7b79a9cb5dbb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc70cd93-ace4-45b9-ae0a-bc0cc45e18ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b02e492d-23d1-4d24-afb9-41600fc48dd3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fdd2afbb-61f0-4bf3-86b3-3973ffc2165e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdactinHotel/Select hotel/TC_005_SearchHotel</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>474bca00-1d7b-423c-8f26-9e3cef59b477</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5c7c61c-a978-4622-adb5-592433bc44e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f070d40-9679-477b-b1b2-256ede52142e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5b04c627-3b91-44ad-8d7c-63f19e5d1d29</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdactinHotel/Select hotel/TC_006_ChangeYourPassword</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3d39505-b4d5-421a-a9d0-38cadf0d6c29</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfad144d-19cb-4889-9748-03e73fc63b24</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f7b8706-890b-4bed-b978-c19060973e8c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>57eb34e6-7d76-4024-9d80-963e3d4ab1b0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdactinHotel/Select hotel/TC_007_Logout</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3decfe28-1be1-4023-babd-37281cbce277</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>653a6fd0-e941-43e4-8100-cc9c7fd76def</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4fd0ad6-6c0a-417b-8b7a-ba3680c86c19</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
