<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Order No_my_itinerary</name>
   <tag></tag>
   <elementGuidId>312203cf-713a-49dc-8599-9e7d7531ce74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='my_itinerary']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#my_itinerary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;My Itinerary&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bfc62826-4d47-4d13-94af-1d48fb1413b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>44380475-c310-4d39-bfee-c71bb2fc69b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>my_itinerary</value>
      <webElementGuid>e27e3181-ec01-4f43-a07b-b4b338c4bf9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>my_itinerary</value>
      <webElementGuid>c6933e72-22c6-4c5d-bd71-f68698e6920f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>reg_button</value>
      <webElementGuid>f2277647-60e0-4b9c-8132-09ae05ee3297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>My Itinerary</value>
      <webElementGuid>885ec7b5-8bf7-440a-947a-44a7d3e986b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>window.location=&quot;BookedItinerary.php&quot;</value>
      <webElementGuid>b06150ba-4b75-4332-85a3-1d275b97cfdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;my_itinerary&quot;)</value>
      <webElementGuid>4b2e5cd6-9316-4e06-8f4b-75ca48ecbee4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='my_itinerary']</value>
      <webElementGuid>16d511ae-c98a-4de4-a9a9-a5cd7bd8e915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='booking_form']/table/tbody/tr[19]/td[2]/input[2]</value>
      <webElementGuid>3480d5ca-fb96-49e9-9e4d-32e4d9aea934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>50313699-ebad-4a37-a138-4218595017e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'my_itinerary' and @id = 'my_itinerary']</value>
      <webElementGuid>b42b13d0-8ab1-49a9-9e29-4c3c7c1410df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
