<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Please Enter your Credit Card CVV Number</name>
   <tag></tag>
   <elementGuidId>38aa073c-0849-42b9-8bce-4c012ba2c55d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='cc_cvv_span']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cc_cvv_span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Please Enter your Credit Card CVV Number&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>b20a777f-664c-42f0-8200-636b1d5504c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cc_cvv_span</value>
      <webElementGuid>1c154bf0-5f7b-4874-bd0c-c9476a1f061b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>reg_error</value>
      <webElementGuid>5ceb761a-6889-44f4-aa9e-9c3263522ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please Enter your Credit Card CVV Number</value>
      <webElementGuid>ed353d5e-4bc3-4829-b953-83211f8aeec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cc_cvv_span&quot;)</value>
      <webElementGuid>ac110a48-557b-48fb-961a-207615abad7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='cc_cvv_span']</value>
      <webElementGuid>e336d907-00d3-4747-9644-57788826d878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='book_hotel_form']/table/tbody/tr[18]/td[2]/label</value>
      <webElementGuid>5ec2d78e-a3ec-4844-b518-cf178bc8426e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::label[1]</value>
      <webElementGuid>11a19a6b-8c63-4bb3-b55e-4a7943fb50fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adactin.com'])[1]/preceding::label[2]</value>
      <webElementGuid>598c4e09-e1b0-4483-b7b8-e81e86848c6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please Enter your Credit Card CVV Number']/parent::*</value>
      <webElementGuid>cccf874f-30b5-4b8f-89c2-b1edbd834890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[18]/td[2]/label</value>
      <webElementGuid>aae13e9b-af77-4508-b689-5fd37d8172a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'cc_cvv_span' and (text() = 'Please Enter your Credit Card CVV Number' or . = 'Please Enter your Credit Card CVV Number')]</value>
      <webElementGuid>ee054429-9832-4267-8a7b-f23698560afd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
