<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Please Enter your 16 Digit Credit Card Number</name>
   <tag></tag>
   <elementGuidId>ebca8eaf-58f6-493a-a47e-a35577f5adb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='cc_num_span']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cc_num_span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Please Enter your 16 Digit Credit Card Number&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>0fd91d32-8b53-430f-973a-48e2f5c57a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cc_num_span</value>
      <webElementGuid>f3cbfa03-c078-418d-bb5f-8e5c89a9e128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>reg_error</value>
      <webElementGuid>eaf52931-a82e-4e62-a48b-95cd06a9dbee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please Enter your 16 Digit Credit Card Number</value>
      <webElementGuid>4617daf4-9bbf-4e07-9441-7e1e650e5a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cc_num_span&quot;)</value>
      <webElementGuid>4794bd2e-0f9a-4d26-b636-8502b6a47c04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='cc_num_span']</value>
      <webElementGuid>1393e227-d0d3-441f-b492-e56de0298d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='book_hotel_form']/table/tbody/tr[15]/td[2]/label[2]</value>
      <webElementGuid>bfc7548c-8100-4b0c-9753-4d7848d1c804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use 16 digit Dummy Data'])[1]/following::label[1]</value>
      <webElementGuid>eaace4e5-662c-4421-83b8-3b981530e73b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::label[2]</value>
      <webElementGuid>d2d8fb8c-712f-4721-a479-d6364778af12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/preceding::label[1]</value>
      <webElementGuid>42c04e91-90e6-4780-bd4c-6c352447348a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please Enter your 16 Digit Credit Card Number']/parent::*</value>
      <webElementGuid>85f0c05d-b711-4c6e-a38e-5a4e785d0aed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]</value>
      <webElementGuid>b0aedb92-df1d-4725-8142-79eb8ec38871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'cc_num_span' and (text() = 'Please Enter your 16 Digit Credit Card Number' or . = 'Please Enter your 16 Digit Credit Card Number')]</value>
      <webElementGuid>68afa441-e8b9-4cf1-9c96-ee3e94d2018d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
