<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Please wait We are processing your Hotel Booking</name>
   <tag></tag>
   <elementGuidId>958a2127-eedc-4ef1-9b01-dcf0a7ecbfe1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='process_span']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#process_span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Please wait! We are processing your Hotel Booking...&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>b5cd283e-e29f-4c87-bc42-d9e41bb9b690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>process_span</value>
      <webElementGuid>c6ca190f-b0ec-4b07-a2ca-99ffdb4300d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>reg_error</value>
      <webElementGuid>d0406271-8482-4785-962d-ae6119122653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please wait! We are processing your Hotel Booking...</value>
      <webElementGuid>3204b93c-264e-4d64-af9d-e1916d41bf24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;process_span&quot;)</value>
      <webElementGuid>2c7d87b0-0c78-4193-97e8-8cdd6b79f320</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='process_span']</value>
      <webElementGuid>50a5dd8e-be32-4b6a-a431-e9224f486737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='book_hotel_form']/table/tbody/tr[19]/td[2]/label</value>
      <webElementGuid>d1e5045f-670a-45a6-bd07-c6fb92a6dcbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::label[2]</value>
      <webElementGuid>569edc9b-da3f-4e87-821c-d341c37b5685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adactin.com'])[1]/preceding::label[1]</value>
      <webElementGuid>8d925e45-e0e5-4671-baa4-160f85ba9d23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please wait! We are processing your Hotel Booking...']/parent::*</value>
      <webElementGuid>032e1f8e-ff50-4933-a7e0-cb0692872c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[19]/td[2]/label</value>
      <webElementGuid>35541bb6-de93-4fdb-9871-1239566af9e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'process_span' and (text() = 'Please wait! We are processing your Hotel Booking...' or . = 'Please wait! We are processing your Hotel Booking...')]</value>
      <webElementGuid>103c3f7e-c246-4021-bafe-92bb95357607</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
