<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select Month</name>
   <tag></tag>
   <elementGuidId>078f70a3-a453-4d18-89f0-beb34f4eae3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cc_exp_month']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cc_exp_month</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cc_exp_month</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9fcc2136-83d5-4a01-8827-2d4d68822af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cc_exp_month</value>
      <webElementGuid>963555a6-8864-4fdc-97dc-8ee0bdf253f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cc_exp_month</value>
      <webElementGuid>becaacbb-d3e4-4575-8a88-46f074375111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select_combobox2</value>
      <webElementGuid>a56b2618-46b9-49e6-a742-b8169686507d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            - Select Month -
            January
            February
            March
			April
			May
			June
			July
			August
			September
			October
			November
            December
          </value>
      <webElementGuid>2d624003-843d-42f3-abe1-e91a9583ef92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cc_exp_month&quot;)</value>
      <webElementGuid>92ebc890-6466-4e69-9ca6-7a4bd6ce26f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cc_exp_month']</value>
      <webElementGuid>76a918bc-2cbb-421b-9bda-90eb1998b944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='book_hotel_form']/table/tbody/tr[17]/td[2]/select</value>
      <webElementGuid>b055c4ce-5ba9-45aa-b988-0586504f172e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::select[1]</value>
      <webElementGuid>c1d9d949-c31f-4160-aafa-80dfa7a9c856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/preceding::select[2]</value>
      <webElementGuid>edf07077-bfe1-4e0d-bc96-a706d261f989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[17]/td[2]/select</value>
      <webElementGuid>256a630d-5cfc-4469-9d67-9c3906e8d22a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'cc_exp_month' and @id = 'cc_exp_month' and (text() = '
            - Select Month -
            January
            February
            March
			April
			May
			June
			July
			August
			September
			October
			November
            December
          ' or . = '
            - Select Month -
            January
            February
            March
			April
			May
			June
			July
			August
			September
			October
			November
            December
          ')]</value>
      <webElementGuid>dc3576e1-68c5-4383-960d-835554a7749a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
