<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CancelBtn</name>
   <tag></tag>
   <elementGuidId>357fb3f8-4df3-4ec0-84e4-3879cb9767ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='booked_form']/table/tbody/tr[2]/td/table/tbody/tr[2]/td[3]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_id_1228345</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Cancel 4G7M9H5G7L&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6fc35346-da7b-47c5-865a-8fe13a661c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn_id_1228345</value>
      <webElementGuid>b807c27d-fdb0-4fc2-8ffe-39813c8be4fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_id_1228345</value>
      <webElementGuid>04ab5a52-fc90-401e-a448-4e2bbf690970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>01b34154-a444-4578-b11a-808a4380f119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Cancel 4G7M9H5G7L</value>
      <webElementGuid>b9a3a1b7-49e9-424d-bfca-68364744a0c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>cancel_booking('1228345','4G7M9H5G7L');</value>
      <webElementGuid>2615f4eb-8e06-4392-baff-1b999b5ab095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_id_1228345&quot;)</value>
      <webElementGuid>62f76c88-dcc0-4ca3-a118-378a1aaa3f05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn_id_1228345']</value>
      <webElementGuid>bdc9c1b1-e304-4706-8d1a-81af56ac422b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='booked_form']/table/tbody/tr[2]/td/table/tbody/tr[2]/td[3]/input</value>
      <webElementGuid>cfb52ebb-cdad-458a-acd3-e88d9efa0ee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/input</value>
      <webElementGuid>c13c1b47-b91d-4bb2-86f9-0d5487368626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'btn_id_1228345' and @id = 'btn_id_1228345' and @type = 'button']</value>
      <webElementGuid>7722bb2b-f1c1-45e0-9406-cac708ff08c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
