<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Total Price (incl. GST)_cancelall</name>
   <tag></tag>
   <elementGuidId>25d8b0b6-69f2-416d-b5b3-4ce78760df29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='cancelall']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;cancelall&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Cancel Selected&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c5659b0b-be2c-475f-8ecd-9a93b9ff7e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cancelall</value>
      <webElementGuid>a7eb614b-0439-4d41-96a1-c519023d0eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>2eb7e1fa-68c8-40ff-ba1a-0f08536fb884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>reg_button</value>
      <webElementGuid>7a36a706-803c-4624-a7e8-adc0f230862d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Cancel Selected</value>
      <webElementGuid>d2822039-893d-4a0d-ad91-89b892509602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return window.confirm('Are you sure want to Cancel Selected?.');</value>
      <webElementGuid>bcd4b4f8-2815-414f-b81c-a07e6b8ebd94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;booked_form&quot;)/table[@class=&quot;login&quot;]/tbody[1]/tr[3]/td[1]/input[@class=&quot;reg_button&quot;]</value>
      <webElementGuid>a2f875f7-102d-47da-a8dd-c5f639a8f9f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='cancelall']</value>
      <webElementGuid>e3f7e689-0add-48d2-926d-e1f66678d467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='booked_form']/table/tbody/tr[3]/td/input</value>
      <webElementGuid>5cde7722-4621-4b8b-80f3-f152f05203aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/input</value>
      <webElementGuid>efb8a08c-02b9-4c5d-ab5d-f62df65f0971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'cancelall' and @type = 'submit']</value>
      <webElementGuid>739ac46a-39d2-4135-ad5d-42a4ade5be3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
