<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Password must contain minimum 6 characters</name>
   <tag></tag>
   <elementGuidId>6141cdad-72ee-4fe3-bc76-6c102373172b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='password_span']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#password_span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Password must contain minimum 6 characters&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e443c658-b6a2-4e00-9f6b-202ee0efac12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password_span</value>
      <webElementGuid>0de7f3de-3376-49ad-81fa-a891906c09d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>reg_error</value>
      <webElementGuid>6d343207-f534-49f4-bec9-152ea1ad6d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password must contain minimum 6 characters</value>
      <webElementGuid>c5b5e2e5-5b6d-4c78-88e0-9371b48938a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password_span&quot;)</value>
      <webElementGuid>696c4c76-0a35-4451-80ec-765fe338a878</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='password_span']</value>
      <webElementGuid>d8e0cbb8-a3cc-438a-a5d5-b9638761ecd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='register_form']/table/tbody/tr[3]/td[2]/label</value>
      <webElementGuid>6c864f30-3b61-4c74-b051-9bd152bca3bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::label[1]</value>
      <webElementGuid>32bc7c85-7757-4774-8c9c-7d506820d35d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::label[1]</value>
      <webElementGuid>534390cc-aad3-46c4-8f61-4f3f659774cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Password must contain minimum 6 characters']/parent::*</value>
      <webElementGuid>57169307-a95a-42ea-8963-09697575c1bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/label</value>
      <webElementGuid>b72fe845-5b89-466b-a475-1af02657492d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'password_span' and (text() = 'Password must contain minimum 6 characters' or . = 'Password must contain minimum 6 characters')]</value>
      <webElementGuid>d6c45a3a-0cfa-4960-bf06-5ae4241830e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
